"""
A real Model Context Protocol (MCP) server exposing the tools the Fraud &
Anomaly Detection Agent uses to cross-reference a "scanned" document
against synthetic historical data.

How this fits together (see orchestrator.py for the wiring):
  1. This file, run as `python -m src.mcp_tools_server`, starts an MCP
     server that speaks the protocol over stdio (standard input/output).
  2. `google.adk.tools.mcp_tool.McpToolset` spawns this file as a CHILD
     PROCESS and talks MCP to it — the same pattern real MCP clients
     (like Claude Desktop) use to talk to MCP servers. There is no shared
     Python state between the two processes; every tool call is a real
     message over the protocol, with real (de)serialization.
  3. The Fraud Detection Agent (agents.py) is handed this toolset and
     calls these tools exactly the way it would call a tool exposed by
     any third-party MCP server.

Why a subprocess instead of, say, an HTTP server? MCP supports several
"transports" (stdio, SSE, streamable HTTP). Stdio is the simplest for a
single-user demo app: no port to open, no network config, and it's
exactly how most local MCP servers run in practice (e.g. a database or
filesystem MCP server running alongside an editor). For a multi-tenant
production deployment you'd more likely use the streamable-HTTP
transport so one long-lived server could serve many client sessions —
that's a one-line change to `mcp.run(transport=...)` plus swapping the
ADK client's `StdioConnectionParams` for `StreamableHTTPConnectionParams`,
noted here for anyone extending this project.

Each tool function below is deliberately a PLAIN, pure Python function
(the `@mcp.tool()` decorator registers it for MCP without changing how
it behaves when called directly) — that's what makes them unit-testable
in tests/test_mcp_tools.py without spinning up a subprocess at all.
"""

from __future__ import annotations

from difflib import SequenceMatcher

from mcp.server.mcpserver import MCPServer

mcp = MCPServer(
    "kyc-triage-tools",
    instructions=(
        "Tools for cross-referencing a KYC applicant's submitted document "
        "against synthetic historical customer data. All data is synthetic "
        "and generated by Faker for demo purposes."
    ),
)


def _names_match(name_a: str, name_b: str, threshold: float = 0.85) -> bool:
    """Fuzzy name match using stdlib difflib (no extra dependency).

    Exact string equality would fail on trivial differences like
    "Jon Smith" vs "Jonathan Smith" or extra whitespace, which are
    realistic OCR/typo scenarios — a real system would use something more
    sophisticated (e.g. phonetic matching, a dedicated identity-resolution
    service), but `SequenceMatcher` is a reasonable, dependency-free
    approximation for a portfolio demo.
    """
    a = name_a.strip().lower()
    b = name_b.strip().lower()
    return SequenceMatcher(None, a, b).ratio() >= threshold


@mcp.tool()
def compare_identity_fields(document: dict, history: dict | None) -> dict:
    """Compare a freshly-extracted document's identity fields against the
    customer's on-file history record (if one exists), and report
    field-level inconsistencies.

    Args:
        document: The ExtractedDocument fields (full_name, date_of_birth,
            address, etc.) as produced by the (simulated) Document
            Analysis step.
        history: The CustomerHistoryRecord fields on file for this
            customer, or None if this is a brand-new customer with no
            prior record.

    Returns:
        A dict describing whether a prior record exists and, if so,
        whether the name/date-of-birth/address on the new document match
        what's already on file.
    """
    if history is None:
        return {
            "has_history_on_file": False,
            "is_new_customer": True,
            "names_match": None,
            "dob_match": None,
            "address_match": None,
        }

    return {
        "has_history_on_file": True,
        "is_new_customer": False,
        "names_match": _names_match(
            document.get("full_name", ""), history.get("full_name_on_file", "")
        ),
        "dob_match": document.get("date_of_birth") == history.get("date_of_birth_on_file"),
        "address_match": _names_match(
            document.get("address", ""), history.get("address_on_file", ""), threshold=0.6
        ),
    }


@mcp.tool()
def check_watchlist_and_flags(history: dict | None) -> dict:
    """Check the customer's on-file record for watchlist status and prior
    risk flags, and compute a simple severity score for those flags.

    Args:
        history: The CustomerHistoryRecord fields on file, or None for a
            brand-new customer (who by definition has no prior flags).

    Returns:
        A dict with `is_on_watchlist`, the list of `prior_flags`, and a
        `flag_severity` score used by the Fraud Agent as one input to its
        overall risk score.
    """
    if history is None:
        return {"is_on_watchlist": False, "prior_flags": [], "flag_severity": 0}

    prior_flags = history.get("prior_flags", [])
    is_on_watchlist = bool(history.get("is_on_watchlist", False))

    # Simple, transparent scoring: watchlist hit dominates; each additional
    # prior flag adds a fixed weight. A real system would tune these
    # weights against labeled outcome data, not hardcode them.
    flag_severity = (50 if is_on_watchlist else 0) + 10 * len(prior_flags)

    return {
        "is_on_watchlist": is_on_watchlist,
        "prior_flags": prior_flags,
        "flag_severity": min(flag_severity, 100),
    }


if __name__ == "__main__":
    mcp.run()
